export const startupDescription = {
    nossaRoca: "O Nossa Roça é um aplicativo mobile desenvolvido para auxiliar agricultores familiares na comercialização de suas colheitas excedentes de forma simples, direta e acessível. A plataforma permite que o agricultor cadastre os alimentos disponíveis e os ofereça para pequenos comércios locais, como mercadinhos, feiras e restaurantes da região. O próprio agricultor fica responsável pela entrega no local combinado. Além de facilitar a venda, o aplicativo contribui para reduzir o desperdício de alimentos e fortalecer a economia local, promovendo a geração de renda para as famílias agricultoras e o acesso a produtos frescos para os compradores. Futuramente, o Nossa Roça também poderá incluir funcionalidades de doação para pessoas físicas e instituições sem fins lucrativos.",

    aromasDoVale: "Espera-se expandir para a escala comercial, a extração, padronização e comercialização do produto: óleo essencial das cascas de laranja, por meio de métodos tradicionais, reconhecidos e de expertise das proponentes. A fim de converter um resíduo agroindustrial em um produto com demanda e de alto valor de mercado.",

    ArtEsfera: "A plataforma ArtEsfera irá contar com três pilares validados em entrevistas com o público-alvo: Assistente Virtual Inteligente (Daeva): No protótipo, usando o modelo GPT-4, a Daeva atenderá a três demandas centrais: orientação sobre procedimentos jurídicos (direitos autorais, contratos), auxílio na construção de precificação justa e elaboração de estratégias de marketing. Bilheteria Virtual: Permitirá que qualquer profissional crie seu evento e venda ingressos diretamente pela plataforma, com uma taxa de serviço variável e justa, incentivando o uso por artistas em todos os estágios de carreira. Dashboard de Cursos: Um espaço onde usuários poderão submeter e vender cursos voltados à profissionalização no setor cultural (mediante curadoria), além de cursos próprios financiados pela ArtEsfera sobre estratégias de crescimento e empreendedorismo para os assinantes. Desta forma, acreditamos que esses três pilares serão capazes de impactar a cena artística e cultural do Estado e do Brasil, diminuindo as desigualdades existentes do cenário, gerando trabalho e educação de qualidade para esses profissionais.",

    zilly: "Nosso produto é um sistema de monitoramento estrutural composto por sensores físicos instalados em pontos estratégicos de edificações, como pilares, vigas e lajes, bem como em infraestruturas essenciais, como pontes e viadutos. Esses sensores captam em tempo real dados sobre deformações, vibrações, deslocamentos e possíveis anomalias na estrutura. As informações são transmitidas para uma plataforma digital, onde são processadas e analisadas por algoritmos de inteligência artificial que realizam análise preditiva para antecipar falhas e padrões de risco. O sistema gera alertas automáticos quando há perigo, além de relatórios técnicos e gráficos que permitem acompanhamento remoto e contínuo da saúde estrutural, oferecendo uma solução eficiente para manutenção preditiva, redução de riscos e otimização de custos.",

    hibuddy: "O Edubuddy é um aplicativo educativo baseado em inteligência artificial que utiliza elementos de gamificação para ensinar conteúdos escolares a crianças do ensino infantil e fundamental I. Inspirado em jogos como o “Pou”, o app oferece uma experiência interativa onde a criança aprende brincando, com atividades adaptadas ao seu nível de conhecimento e estilo de aprendizagem. A IA funciona localmente no dispositivo, garantindo maior privacidade e acessibilidade. O objetivo é tornar o processo de aprendizagem mais divertido, inclusivo e eficiente — inclusive para crianças neurodivergentes.",

    desvenda: "Desvenda é um aplicativo mobile que atua como um guia inteligente de experiências locais, conectando usuários a eventos, gastronomia, cultura e lazer com base em geolocalização e preferências pessoais. Por meio de uma interface moderna e inspirada em redes sociais, o app permite buscar, filtrar e interagir com rolês próximos, promovendo descobertas personalizadas, planejamento de agenda e integração com rotas de transporte. Além de atender o público em busca de novas vivências, o Desvenda oferece espaço para estabelecimentos e produtores locais divulgarem seus serviços de forma segmentada e eficiente, fortalecendo a economia criativa e o turismo regional.",

    sera462: "O SERA462 é uma plataforma gamificada de educação que integra o conteúdo escolar a uma experiência imersiva em formato de jogo, onde os alunos desvendam os mistérios do planeta SERA462 ao responderem atividades propostas pelos professores. Com o apoio de uma inteligência artificial, os professores criam e personalizam questões que são inseridas automaticamente no game. Além disso, a plataforma permite que professores e gestores acompanhem o desempenho dos alunos em tempo real, promovendo maior engajamento, eficiência e personalização no processo de ensino-aprendizagem.",

    roleApp: "Rolê App é uma plataforma digital de curadoria colaborativa que conecta usuários a experiências autênticas de lazer (bares, eventos culturais, passeios) em tempo real. Como funciona: Para usuários: Busca personalizada por localização, tipo de experiência e orçamento. Recomendações baseadas em machine learning e avaliações da comunidade. Atualizações dinâmicas de eventos e promoções. Para estabelecimentos: Perfil digital com gestão de eventos, promoções e analytics de público. Planos de assinatura para maior visibilidade (ex.: destaque no app).",

    serFit: "Soluciona o problema descrito por vários pacientes na hora da correria do dia a dia ter que escolher o alimento por aplicativo e não ter uma variedade de fast food fit e comidas saudáveis, principalmente para quem quer aderir a nova onda do momento que é ser Fit, ou está no processo de reeducação alimentar e entra nos aplicativos tradicionais e são tentados a escolher o que já de costume escolherem ou seja o não saudável.",

    lamparinaSocial: "O serviço envolve a formação continuada de professores durante a implementação de um programa de educação midiática que envolve o uso de softwares livres para a criação de uma rede social escolar, cujo objetivo é promover a colaboração, a aprendizagem significativa, o letramento digital e o fortalecimento dos vínculos entre a comunidade escolar através de práticas de autogestão desta rede.",

    mype: "O produto é uma plataforma de performance e treino inteligente, entregue via um software em aplicativo mobile. O serviço utiliza visão computacional avançada para transformar a câmera do smartphone em um laboratório de biomecânica pessoal. O processo começa com um mapeamento da estrutura corporal e fisiologia do usuário. Durante o treino, nosso algoritmo analisa cada repetição em tempo real, focando em métricas cruciais de performance como execução, cadência, amplitude e controle do movimento. Além de orientações instantâneas por áudio e alertas visuais para correção imediata, o usuário recebe relatórios detalhados e replays em vídeo de suas séries. Esses vídeos destacam os pontos de falha e acerto, permitindo uma análise precisa para otimizar a técnica. Essencialmente, resolvemos a falta de orientação de elite, maximizando a performance e a segurança do treino de forma totalmente personalizada, mediante as particularidades fisicas e objetivos do usuário.",
    
    oxeComprei: "Meu produto é um aplicativo de marketplace local, criado para ajudar pequenos empreendedores a divulgarem e venderem seus produtos de forma mais organizada, atrativa e profissional. Ele funciona como uma vitrine digital, onde lojas da região podem anunciar itens como roupas, acessórios, cosméticos e outros, facilitando a conexão com clientes próximos. Além de apoiar novos negócios a ganharem visibilidade, o aplicativo também contribui para melhorar a entrega, já que as vendas acontecem dentro da mesma cidade ou região, reduzindo tempo e custo logístico.",

    beyondTheArid: "O OURIECO é um umidificador solar desenvolvido para mitigar os efeitos do clima seco em regiões semiáridas. Utilizando princípios de resfriamento passivo aliado à energia solar, o equipamento atua na criação de microclimas mais úmidos e amenos, tanto em ambientes agrícolas quanto urbanos. Seu funcionamento permite reduzir a temperatura, aumentar a umidade relativa do ar e melhorar as condições para o cultivo de alimentos, especialmente de Plantas Alimentícias Não Convencionais(PANCs), que são adaptadas ao clima árido. Além disso, seu uso contribui para o conforto térmico emespaços urbanos, como escolas, praças e residências, e auxilia na preservação de alimentos esementes. O produto é de baixo custo, modular, fácil de instalar e com manutenção simples, oferecendouma solução sustentável e acessível, com potencial para escalar em diferentes contextos. Integrado ao OURIECO, o serviço da Beyond the Arid inclui também capacitação técnica para agricultores e comunidades, além de suporte no desenvolvimento de práticas agrícolas regenerativas, promovendo segurança alimentar, resiliência climática e geração de renda.",

    avaliacaoEconomica: "“Avaliar é uma condição imprescindível para a gestão de programas/projetos econômicos e sociais, pois gera conhecimento sobre a ação que se realiza, fornece dados para verificação da efetividade do caminho escolhido e permite aprimoramento e correção de rotas, quando necessário. Implementação de metodologias de Impacto e Resultados por meio da Análise de Dados e Estatística Aplicada e a Probabilidade a 95% de confiança. Os métodos irão permitir afirmar com segurança quais as atividades mais impactaram o principal indicador de interesse.",

    hubPajeu: "Hub criativo que conecta empresas e profissionais para estruturar carreiras artísticas e fortalecer o mercado cultural do Sertão do Pajeú com serviços integrados e suporte técnico especializado.",

    detektAI: "A PolicIAtiva é uma plataforma tecnológica que utiliza inteligência artificial e processamento delinguagem natural para automatizar a análise de boletins de ocorrência (BO). Ela integra dados criminais em tempo real, detecta padrões e gera modelos preditivos para apoiar as forças de segurança pública na prevenção e combate à criminalidade. A solução conecta sistemas governamentais existentes, automatiza fluxos de trabalho e oferece dashboards e relatórios que facilitam a tomada de decisão estratégica, otimizando o patrulhamento e a resposta a incidentes. Além disso, a plataforma inclui treinamento e suporte contínuo para garantir a adoção eficaz pelos usuários.",

    freteGesso: "Nosso serviço é um aplicativo móvel que conecta motoristas autônomos a empresas com cargas de gesso e derivados no Polo Gesseiro. A plataforma facilita a contratação direta, elimina intermediários, agiliza o transporte e reduz custos com agenciamento. O sistema oferece geolocalização, histórico de fretes, avaliação de motoristas e comunicação em tempo real, promovendo eficiência, transparência e economia para todos os envolvidos.",

    neureon: "É uma Interface-Cerebro-Maquina (BCI) integrada a um sistema de automação residencial (ESPHome) um dispositivo ergonomico e compacto com eletrodos para a aquisição dos biosinais de forma não invasiva. Ele interage com os demais dispositivos conectados na rede, sejam luzes, leds, ar condicionado, sistemas de som e etc. Seu propósito é o bem estar, portando ele também monitora a qualidade do sono e foco.",

    vitally: "Barra de cereal natural sem adição de açucar ou aditivos, adoçado com banana e uva passas, ideal para pessoas que não podem ingerir açúcar ou desejam uma alimentação saudável.",

    inovacaoSustentavelEco: "Produto é uma calda orgânica feita por produtos encontrados na própria Fazenda sendo ultilizado cinzas de fogão a lenha,esterco de ovinos frutas estragadas e aquela parte chamada de coração da bananeira,sendo picado e vários outros tipos de frutas,onde é colocado em um recipiente de dois mil litros de agua, depois de está misturado todos mexer diariamente por 25 dias até a sua fermentação. Onde será disponibilizado potássio,nitrogênio e fósforo que são os micronutrientes essenciais.",

    ecoSolDoAraripe: "Com a sujidade nos módulos fotovoltaicos, estima-se que se perde até 35% da geração de energia em grandes usinas solares, o robô de limpeza com dois colaboradores levam o robô na linha de módulos e já fazem uma inspeção visual da sujidade que esta sendo combatida. Com isso o a limpeza é feita uniformemente com rápidez e utilizando até 70% menos água comparando com o modo manual. Em grandes usinas são acima de 100 mil módulos, variando os seus tamanhos, podendo chegar em uma única usina, mais de 2 milhões de placas solares, tornando inviável a limpeza manual.", 

    adbr: "A AI Agency oferece uma solução inovadora baseada em agentes de inteligência artificial personalizados, desenvolvidos para automatizar processos críticos em pequenas e médias empresas brasileiras. Cada agente atua como um “colaborador digital” que executa tarefas específicas com agilidade, precisão e integração total aos sistemas do negócio. A seguir, os principais agentes e suas funções: 🔹 ADBR AI FrontDesk – Atendimento automático e inteligente. Atende clientes em múltiplos canais (site, WhatsApp, redes sociais), tira dúvidas, resolve problemas e gera uma experiência profissional e imediata.🔹 ADBR AI Schedule – Agendamento sem erro. Gerencia compromissos, evita conflitos de horário e reduz faltas, otimizando agendas com eficiência. 🔹 ADBR AI Instruction – Suporte e treinamento automatizado. Oferece guias, tutoriais e orientações técnicas para equipes e clientes, garantindo aprendizado contínuo. 🔹 ADBR AI Insight – Análise de dados em tempo real. Gera insights estratégicos a partir de dados internos, ajudando na tomada de decisão com base em evidências. 🔹 ADBR AI Flow – Execução de processos automatizados. Executa tarefas rotineiras e conecta etapas de trabalho, reduzindo retrabalho e aumentando produtividade. 🔹 ADBR AI Monitor – Acompanhamento operacional. Monitora indicadores, detecta falhas e emite alertas para garantir fluidez operacional. 🔹 ADBR AI KPI – Relatórios e dashboards inteligentes. Fornece relatórios automáticos e visualizações de desempenho, facilitando o controle e a gestão. 🔹 ADBR AI Alert – Notificações e avisos proativos. Envia alertas automáticos para prazos, pendências, oportunidades ou riscos. 🔹 ADBR AI Engage – Relacionamento com clientes. Mantém contato com clientes ativos e inativos, aumenta a fidelização e melhora a experiência pós-venda. 🔹 ADBR AI Optimus – Otimização de processos internos. Identifica gargalos e automatiza fluxos para melhorar eficiência e reduzir custos operacionais. 🔹 ADBR AI Automate – Execução de tarefas repetitivas Assume atividades manuais (envio de e-mails, organização de dados, atualização de planilhas). 🔹 ADBR AI Planer – Planejamento e organização. Executa tarefas ligadas à gestão, cronogramas e projetos, oferecendo suporte tático. 🔹 ADBR AI DocProcess – Análise de documentos. Descreva o seu produto, serviço ou processo * 14/06/2025, 12:14 Inscrição para o Sertão Inovador - 2025.2, Lê, interpreta e extrai informações de contratos, licitações, laudos e documentos operacionais. Cada agente atende uma dor real enfrentada pelas empresas brasileiras, permitindo que elas automatizem processos, escalem o atendimento e tomem decisões mais inteligentes — tudo com baixo custo, rápida implantação e alta aplicabilidade.",  

    automatech: "Nosso serviço oferece soluções completas de automação e monitoramento inteligente de equipamentos, voltadas para hospitais, instituições educacionais e pequenas empresas. O projeto inclui: Instalação de sensores e dispositivos de automação para acompanhar o funcionamento de máquinas e equipamentos; Aplicativo móvel e plataforma online para monitoramento em tempo real, com visualização de dados, alertas de falhas e histórico de desempenho; Sistema de manutenção preventiva e corretiva, com agendamento automático e notificações baseadas em dados coletados; Suporte técnico híbrido, que combina visitas presenciais com assistência virtual para solução de falhas simples de forma rápida e autônoma pelo próprio cliente. Essa solução permite maior controle, reduz o tempo de inatividade dos equipamentos, previne falhas graves, diminui custos operacionais e leva tecnologia de ponta a um público que normalmente não tem acesso fácil a esses recursos.",

    SalãoEscolaBeleza: "O projeto “Beleza que Transforma” tem como objetivo criar uma escola profissionalizante na área da beleza, oferecendo capacitação técnica e empreendedora para mulheres da região. Mais que estética, o projeto visa gerar transformação social, desenvolvimento econômico local e autonomia financeira para mulheres, sobretudo em regiões do sertão com menos acesso a oportunidades. Objetivo Geral: Criar uma escola de formação na área da beleza, promovendo capacitação técnica, desenvolvimento profissional, geração de renda e transformação social, com foco na independência financeira e nofortalecimento da economia local.",

    agroTronix: "O sistema de contagem de caixas é uma plataforma online desenvolvida para registrar automaticamente, em tempo real, a quantidade de caixas embaladas por cada colaborador (embaladeira) em uma linha de produção. Cada embaladeira possui um código exclusivo, lido por um leitor de código de barras conectado a um Raspberry Pi, o que elimina a necessidade de anotações manuais. Os dados são enviados diretamente para o sistema, onde podem ser visualizados em gráficos, rankings e relatórios, oferecendo uma gestão clara e eficiente da produtividade diária. O sistema é acessível por qualquer dispositivo com navegador, sem necessidade de instalação.",

    redeSertaoCriativo: "O serviço proposto será desenvolvido por meio da criação de uma instituição sem fins lucrativos que atuará com foco na formação, assessoria técnica e apoio estruturado a artistas, técnicos e grupos culturais dos sertões pernambucanos. Seu objetivo é oferecer suporte contínuo na elaboração, inscrição, execução e prestação de contas de projetos culturais, além de promover capacitações presenciais e online voltadas à realidade da cultura popular e periférica. O processo envolve: Atendimento técnico individual ou em grupo para orientação sobre editais, legislação cultural e gestão de projetos; Elaboração de projetos e consultorias personalizadas para artistas e grupos; Realização de cursos e oficinas sobre produção cultural, prestação de contas, marketing, comunicação e outros temas estratégicos; Fortalecimento de uma rede regional de profissionais da cultura, com valorização da produção local e ampliação da autonomia técnica e institucional de agentes culturais. O serviço busca atuar como ponte entre os agentes culturais dos sertões e as oportunidades existentes no ecossistema cultural, democratizando o acesso ao fomento público e promovendo sustentabilidade para o setor.",

    edi: "Desenvolver equipamentos e uma plataforma que serviram de apoio para educadores, profissionais da saúde para auxiliar seus alunos e ou clientes em diversas áreas do conhecimento",

    agroEventos: "A Agro Eventos tende a ser uma empresa especializada na cobertura, criação e divulgação de conteúdos relacionados ao setor do agronegócio. Com foco na produção de materiais audiovisuais e textos para redes sociais, portais e parceiros do agronegócio, buscamos impulsionar a visibilidade e o sucesso de produtores, empresas e eventos do agro.",

    ZeaTech: "A ZeaTech desenvolve um sistema inteligente de monitoramento para armazenagem agrícola, quecombina sensores IoT, análise de dados em tempo real e inteligência preditiva. O sistema é compostopor um conjunto de sensores embarcados que medem variáveis críticas como temperatura, umidade, CO2, infestação por pragas, partículas suspensas no ar e volume de grãos, com conectividade Wi-Fi e alimentação autônoma. Esses dados são enviados para um painel acessível via aplicativo móvel, onde o produtor pode acompanhar as condições do silo ou câmara fria em tempo real, receber alertas automáticos e acessar diagnósticos preditivos baseados em inteligência artificial. O sistema visa prevenir perdas pós-colheita, evitar riscos de explosão e deterioração dos produtos, além de oferecer maior rastreabilidade e segurança alimentar. Além de grãos, a solução está sendo adaptada para o monitoramento em câmaras frias de frutas e hortaliças, ampliando seu campo de aplicação. A ZeaTech entrega uma tecnologia de fácil uso, acessível ao pequeno e médio produtor, com potencial de expansão para cooperativas, associações e indústrias do setor agroalimentar.",

    aquatech: "O projeto consiste na implementação de um sistema de aquaponia, uma tecnologia que integra de forma simbiótica a criação de peixes (aquicultura) com o cultivo de hortaliças (hidroponia) em um ciclo fechado e sustentável. No sistema, a água rica em nutrientes provenientes dos dejetos dos peixes é bombeada para irrigar as plantas, que, por sua vez, filtram a água e a devolvem limpa para o tanque dos peixes, criando um ecossistema equilibrado. Esse processo inovador não utiliza agrotóxicos, economiza até 90% de água em comparação à agricultura tradicional e pode ser implantado em espaços pequenos, médios ou grandes, tanto em áreas urbanas quanto rurais. Além da produção de alimentos saudáveis, o projeto tem caráter educacional e social, promovendo oficinas, formação de jovens multiplicadores e conscientização ambiental, com potencial de geração de renda, segurança alimentar e replicação em escolas, comunidades e cooperativas.",
    
    eduHub: "Diferente de plataformas genéricas ou fragmentadas, nossa solução é focada no contexto regional, reunindo todos os cursos locais em um só lugar, com ferramentas de comparação inteligente, dados atualizados do mercado de trabalho e avaliações reais de alunos. Essa integração proporciona uma experiência completa e estratégica para quem busca formação alinhada às oportunidades da região.",

    agroGestaoConsultoria: "A empresa tem como finalidade. Direcionar pequenos e médios produtores na gestão financeira e de custos de produção. Além de oferecer consultoria de campo focando no melhor desenvolvimento da cadeia produtiva.",
}